// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_About = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_time_screen_init);
    }
}

// build funtions

void ui_About_screen_init(void)
{
    ui_About = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton2 = lv_imagebutton_create(ui_About);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back32_png, NULL);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_back32_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 32);
    lv_obj_set_height(ui_ImgButton2, 32);
    lv_obj_set_x(ui_ImgButton2, 1);
    lv_obj_set_y(ui_ImgButton2, 146);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_ImgButton2, 30);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_About_screen_destroy(void)
{
    if(ui_About) lv_obj_del(ui_About);

    // NULL screen variables
    ui_About = NULL;
    ui_ImgButton2 = NULL;

}
