// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_flash_screen = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_flash_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 5000, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_flash_screen_screen_init(void)
{
    ui_flash_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_flash_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_flash_screen, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flash_screen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_flash_screen);
    lv_image_set_src(ui_Image4, &ui_img_kafkar_logo_no_boarder_100_white_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image4, 6);
    lv_obj_set_y(ui_Image4, -2);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_flash_screen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, -113);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "FocusTimer");

    ui_Label5 = lv_label_create(ui_flash_screen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 4);
    lv_obj_set_y(ui_Label5, 108);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Kafkar.com");

    lv_obj_add_event_cb(ui_flash_screen, ui_event_flash_screen, LV_EVENT_ALL, NULL);

}

void ui_flash_screen_screen_destroy(void)
{
    if(ui_flash_screen) lv_obj_del(ui_flash_screen);

    // NULL screen variables
    ui_flash_screen = NULL;
    ui_Image4 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;

}
