// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_FLASH_SCREEN_H
#define UI_FLASH_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_flash_screen
extern void ui_flash_screen_screen_init(void);
extern void ui_flash_screen_screen_destroy(void);
extern void ui_event_flash_screen(lv_event_t * e);
extern lv_obj_t * ui_flash_screen;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

