// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_FOCUS_H
#define UI_FOCUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Focus
extern void ui_Focus_screen_init(void);
extern void ui_Focus_screen_destroy(void);
extern lv_obj_t * ui_Focus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

