// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_SetupFocus = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_time_screen_init);
    }
}

// build funtions

void ui_SetupFocus_screen_init(void)
{
    ui_SetupFocus = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SetupFocus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_SetupFocus);
    lv_obj_set_width(ui_Arc1, 285);
    lv_obj_set_height(ui_Arc1, 280);
    lv_obj_set_x(ui_Arc1, 4);
    lv_obj_set_y(ui_Arc1, 5);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    ui_ImgButton5 = lv_imagebutton_create(ui_SetupFocus);
    lv_imagebutton_set_src(ui_ImgButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back32_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 32);
    lv_obj_set_height(ui_ImgButton5, 32);
    lv_obj_set_x(ui_ImgButton5, -1);
    lv_obj_set_y(ui_ImgButton5, 145);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_ImgButton5, 30);

    ui_Label3 = lv_label_create(ui_SetupFocus);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "88:88");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_MomoTrustDisplay, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);

}

void ui_SetupFocus_screen_destroy(void)
{
    if(ui_SetupFocus) lv_obj_del(ui_SetupFocus);

    // NULL screen variables
    ui_SetupFocus = NULL;
    ui_Arc1 = NULL;
    ui_ImgButton5 = NULL;
    ui_Label3 = NULL;

}
