// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SETUPFOCUS_H
#define UI_SETUPFOCUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetupFocus
extern void ui_SetupFocus_screen_init(void);
extern void ui_SetupFocus_screen_destroy(void);
extern lv_obj_t * ui_SetupFocus;
extern lv_obj_t * ui_Arc1;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

