// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_TIME_H
#define UI_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_time
extern void ui_time_screen_init(void);
extern void ui_time_screen_destroy(void);
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_hours;
extern lv_obj_t * ui_pointhour;
extern lv_obj_t * ui_minuts;
extern lv_obj_t * ui_pointminut;
extern lv_obj_t * ui_seconds;
extern lv_obj_t * ui_date;
extern void ui_event_ImgButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonSettings;
extern void ui_event_ImgButtonFocus(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonFocus;
// CUSTOM VARIABLES
extern lv_obj_t * uic_hours;
extern lv_obj_t * uic_pointhour;
extern lv_obj_t * uic_minuts;
extern lv_obj_t * uic_pointminut;
extern lv_obj_t * uic_seconds;
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_ImgButtonSettings;
extern lv_obj_t * uic_ImgButtonFocus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

