// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_ImgButtonFocus;
lv_obj_t * uic_ImgButtonSettings;
lv_obj_t * uic_date;
lv_obj_t * uic_seconds;
lv_obj_t * uic_pointminut;
lv_obj_t * uic_minuts;
lv_obj_t * uic_pointhour;
lv_obj_t * uic_hours;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_hours = NULL;
lv_obj_t * ui_pointhour = NULL;
lv_obj_t * ui_minuts = NULL;
lv_obj_t * ui_pointminut = NULL;
lv_obj_t * ui_seconds = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_ImgButtonSettings = NULL;
lv_obj_t * ui_ImgButtonFocus = NULL;
// event funtions
void ui_event_ImgButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_About, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_About_screen_init);
    }
}

void ui_event_ImgButtonFocus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetupFocus, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SetupFocus_screen_init);
    }
}

// build funtions

void ui_time_screen_init(void)
{
    ui_time = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hours = lv_label_create(ui_time);
    lv_obj_set_width(ui_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hours, -119);
    lv_obj_set_y(ui_hours, -13);
    lv_obj_set_align(ui_hours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hours, "88");
    lv_obj_remove_flag(ui_hours, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_hours, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hours, &ui_font_MomoTrustDisplay, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pointhour = lv_label_create(ui_time);
    lv_obj_set_width(ui_pointhour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pointhour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pointhour, -57);
    lv_obj_set_y(ui_pointhour, -19);
    lv_obj_set_align(ui_pointhour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pointhour, ":");
    lv_obj_remove_flag(ui_pointhour, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_pointhour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pointhour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pointhour, &ui_font_MomoTrustDisplay, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minuts = lv_label_create(ui_time);
    lv_obj_set_width(ui_minuts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minuts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minuts, 7);
    lv_obj_set_y(ui_minuts, -11);
    lv_obj_set_align(ui_minuts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minuts, "88");
    lv_obj_remove_flag(ui_minuts, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_minuts, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minuts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minuts, &ui_font_MomoTrustDisplay, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pointminut = lv_label_create(ui_time);
    lv_obj_set_width(ui_pointminut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pointminut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pointminut, 67);
    lv_obj_set_y(ui_pointminut, -20);
    lv_obj_set_align(ui_pointminut, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pointminut, ":");
    lv_obj_remove_flag(ui_pointminut, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_pointminut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pointminut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pointminut, &ui_font_MomoTrustDisplay, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seconds = lv_label_create(ui_time);
    lv_obj_set_width(ui_seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seconds, 133);
    lv_obj_set_y(ui_seconds, -12);
    lv_obj_set_align(ui_seconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_seconds, "88");
    lv_obj_remove_flag(ui_seconds, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_seconds, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_seconds, &ui_font_MomoTrustDisplay, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_time);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 2);
    lv_obj_set_y(ui_date, 51);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "10/01/2026");
    lv_obj_set_style_text_font(ui_date, &ui_font_ZalandoSansExpandedVariableFontwght, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonSettings = lv_imagebutton_create(ui_time);
    lv_imagebutton_set_src(ui_ImgButtonSettings, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_settings32_png, NULL);
    lv_imagebutton_set_src(ui_ImgButtonSettings, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_settings32_png, NULL);
    lv_obj_set_width(ui_ImgButtonSettings, 32);
    lv_obj_set_height(ui_ImgButtonSettings, 32);
    lv_obj_set_x(ui_ImgButtonSettings, 7);
    lv_obj_set_y(ui_ImgButtonSettings, 151);
    lv_obj_set_align(ui_ImgButtonSettings, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_ImgButtonSettings, 30);

    ui_ImgButtonFocus = lv_imagebutton_create(ui_time);
    lv_imagebutton_set_src(ui_ImgButtonFocus, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_372656621, NULL);
    lv_obj_set_width(ui_ImgButtonFocus, 32);
    lv_obj_set_height(ui_ImgButtonFocus, 32);
    lv_obj_set_x(ui_ImgButtonFocus, 3);
    lv_obj_set_y(ui_ImgButtonFocus, -141);
    lv_obj_set_align(ui_ImgButtonFocus, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_ImgButtonFocus, 30);

    lv_obj_add_event_cb(ui_ImgButtonSettings, ui_event_ImgButtonSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonFocus, ui_event_ImgButtonFocus, LV_EVENT_ALL, NULL);
    uic_hours = ui_hours;
    uic_pointhour = ui_pointhour;
    uic_minuts = ui_minuts;
    uic_pointminut = ui_pointminut;
    uic_seconds = ui_seconds;
    uic_date = ui_date;
    uic_ImgButtonSettings = ui_ImgButtonSettings;
    uic_ImgButtonFocus = ui_ImgButtonFocus;

}

void ui_time_screen_destroy(void)
{
    if(ui_time) lv_obj_del(ui_time);

    // NULL screen variables
    ui_time = NULL;
    uic_hours = NULL;
    ui_hours = NULL;
    uic_pointhour = NULL;
    ui_pointhour = NULL;
    uic_minuts = NULL;
    ui_minuts = NULL;
    uic_pointminut = NULL;
    ui_pointminut = NULL;
    uic_seconds = NULL;
    ui_seconds = NULL;
    uic_date = NULL;
    ui_date = NULL;
    uic_ImgButtonSettings = NULL;
    ui_ImgButtonSettings = NULL;
    uic_ImgButtonFocus = NULL;
    ui_ImgButtonFocus = NULL;

}
