// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
#include "ui_helpers.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_About.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_flash_screen.h"


///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_kafkar_logo_no_boarder_100_white_png); // assets/kafkar_logo_no_boarder_100_white.png
LV_IMG_DECLARE(ui_img_back32_png);     // assets/back32.png
LV_IMG_DECLARE(ui_img_settings32_png); // assets/settings32.png

// FONTS
LV_FONT_DECLARE(ui_font_ArchivoBlackRegular);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_MomoTrustDisplay);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
